apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3-openjdk-11
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /root/.m2/repository
          name: maven-repo
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
    - name: kubectl
      image: alpine/k8s:latest
      command:
        - cat
      tty: true
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo
